server.port=${SERVER_PORT:8082}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/tradewise_portfolio_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:tradewise_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:tradewise_pass}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true