server.port=${SERVER_PORT:8087}

spring.data.jpa.repositories.enabled=false
spring.datasource.url=
spring.jpa.hibernate.ddl-auto=none

portfolio.service.url=${PORTFOLIO_SERVICE_URL:http://portfolio-service:8082}
market-data.service.url=${MARKET_DATA_SERVICE_URL:http://market-data-service:8084}