spring.application.name=market-data-service

server.port=${SERVER_PORT:8084}

tradewise.app.finnhub.apikey=${FINNHUB_API_KEY:d43mb5pr01qvet2pnvtgd43mb5pr01qvet2pnvu0}
tradewise.app.finnhub.websocket.url=${FINNHUB_WEBSOCKET_URL:wss://ws.finnhub.io}

tradewise.app.alphavantage.baseurl=${ALPHAVANTAGE_BASE_URL:https://www.alphavantage.co/query}
tradewise.app.alphavantage.apikey=${ALPHAVANTAGE_API_KEY:demo}

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer