spring.application.name=user-service

server.port=${SERVER_PORT:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/tradewise_user_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:tradewise_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:tradewise_pass}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

tradewise.app.jwtSecret=${JWT_SECRET:EaW7nZJ3p6v9y$B&E)H@McQfTjWnZr4u7x!A%D*G-KaPdSgUkXp2s5v8y/B?E(H+}
tradewise.app.jwtExpirationMs=${JWT_EXPIRATION_MS:86400000}

portfolio.service.url=${PORTFOLIO_SERVICE_URL:http://portfolio-service:8082}
strategy.service.url=${STRATEGY_SERVICE_URL:http://strategy-service:8083}

logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.tradewise.userservice=DEBUG